# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-26 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0012_proxy_config_host'),
    ]

    operations = [

    ]
